name: Update Calendar

on:
  schedule:
    - cron: "0 * * * *"   # jede Stunde
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install requests
      - run: python filter.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add calendar.ics
          git commit -m "Update filtered calendar" || echo "No changes"
          git push
